/afs/cern.ch/user/j/jheikkil/.local/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
/afs/cern.ch/user/j/jheikkil/.local/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
/afs/cern.ch/user/j/jheikkil/.local/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Error in <TSystem::ExpandFileName>: input: $HOME/.root.mimes, output: $HOME/.root.mimes
Traceback (most recent call last):
  File "analyzeHgcalL1Tntuple.py", line 519, in <module>
    main(analyze=analyze)
  File "analyzeHgcalL1Tntuple.py", line 334, in main
    cfgfile = yaml.load(stream)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 522, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/py2-PyYAML/3.11-gnimlf/lib/python2.7/site-packages/yaml/constructor.py", line 513, in find_python_name
    module.__name__), mark)
ConstructorError: while constructing a Python object
cannot find 'my_plotter' in the module 'python.plotters_config'
  in "myselection.yaml", line 29, column 15
